name: Model Auto-Update

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at noon UTC
  workflow_dispatch:       # Enable manual runs

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install scikit-learn
          run: pip install scikit-learn 
      - name: Update model
        run: |
          python update_model.py
          
      - name: Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add model.pkl
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')"
          git push
